--
-- PostgreSQL database dump
--

\restrict b9jSiXuuLPbTTalalLliZY65CE4iFfOflnQ65jZXEi9hJLY4oaxvzIWRnNTCSHA

-- Dumped from database version 17.10 (Debian 17.10-0+deb13u1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-0+deb13u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: arbitro; Type: TABLE; Schema: public; Owner: develop
--

CREATE TABLE public.arbitro (
    id_arbitro bigint NOT NULL,
    apellido character varying(255),
    categoria character varying(255),
    contrasenia character varying(255) NOT NULL,
    disponible_domingo boolean,
    disponible_sabado boolean,
    estado_sistema boolean,
    nombre character varying(255),
    talle_camiseta character varying(255),
    talle_short character varying(255),
    whatsapp character varying(255),
    tiene_auto boolean,
    CONSTRAINT arbitro_categoria_check CHECK (((categoria)::text = ANY ((ARRAY['AVANZADO'::character varying, 'INTERMEDIO'::character varying, 'PRINCIPAL_1'::character varying, 'PRINCIPAL_2'::character varying, 'PRINCIPAL_3'::character varying, 'PRINCIPAL_4'::character varying, 'ASISTENTE'::character varying, 'INICIAL'::character varying])::text[])))
);


ALTER TABLE public.arbitro OWNER TO develop;

--
-- Name: arbitro_id_arbitro_seq; Type: SEQUENCE; Schema: public; Owner: develop
--

ALTER TABLE public.arbitro ALTER COLUMN id_arbitro ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.arbitro_id_arbitro_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: caja; Type: TABLE; Schema: public; Owner: develop
--

CREATE TABLE public.caja (
    id_caja bigint NOT NULL,
    activo boolean,
    anio integer NOT NULL,
    nombre character varying(100) NOT NULL,
    saldo_actual numeric(12,2) NOT NULL
);


ALTER TABLE public.caja OWNER TO develop;

--
-- Name: caja_id_caja_seq; Type: SEQUENCE; Schema: public; Owner: develop
--

ALTER TABLE public.caja ALTER COLUMN id_caja ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.caja_id_caja_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cancha; Type: TABLE; Schema: public; Owner: develop
--

CREATE TABLE public.cancha (
    id_cancha bigint NOT NULL,
    categoria character varying(255),
    estado boolean,
    fuera_de_juego boolean,
    nombre_cancha character varying(255),
    necesita_viaje boolean,
    CONSTRAINT cancha_categoria_check CHECK (((categoria)::text = ANY ((ARRAY['FUTBOL_11'::character varying, 'FUTBOL_10'::character varying, 'FUTBOL_9'::character varying])::text[])))
);


ALTER TABLE public.cancha OWNER TO develop;

--
-- Name: cancha_seq; Type: SEQUENCE; Schema: public; Owner: develop
--

CREATE SEQUENCE public.cancha_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.cancha_seq OWNER TO develop;

--
-- Name: concepto_gasto; Type: TABLE; Schema: public; Owner: develop
--

CREATE TABLE public.concepto_gasto (
    id_concepto_gasto integer NOT NULL,
    descripcion character varying(255),
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.concepto_gasto OWNER TO develop;

--
-- Name: concepto_gasto_id_concepto_gasto_seq; Type: SEQUENCE; Schema: public; Owner: develop
--

ALTER TABLE public.concepto_gasto ALTER COLUMN id_concepto_gasto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.concepto_gasto_id_concepto_gasto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: designacion; Type: TABLE; Schema: public; Owner: develop
--

CREATE TABLE public.designacion (
    id_designacion bigint NOT NULL,
    cantidad_partidos integer,
    estado_designacion integer NOT NULL,
    etapa_campeonato character varying(255),
    fecha timestamp(6) without time zone,
    id_canchah bigint,
    detalle_extra character varying(255),
    editable boolean,
    CONSTRAINT designacion_etapa_campeonato_check CHECK (((etapa_campeonato)::text = ANY ((ARRAY['FECHA_NORMAL'::character varying, 'FECHA_PICANTE'::character varying, 'CLASIFICACION'::character varying, 'CRUCES'::character varying, 'SEMIFINAL'::character varying, 'FINAL'::character varying])::text[])))
);


ALTER TABLE public.designacion OWNER TO develop;

--
-- Name: designacion_id_designacion_seq; Type: SEQUENCE; Schema: public; Owner: develop
--

ALTER TABLE public.designacion ALTER COLUMN id_designacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.designacion_id_designacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: designados; Type: TABLE; Schema: public; Owner: develop
--

CREATE TABLE public.designados (
    id_designados bigint NOT NULL,
    categoria_arbitro character varying(255),
    monto_percibido numeric(38,2),
    partidos_dirigidos integer,
    id_arbitroh bigint,
    id_designacionh bigint,
    CONSTRAINT designados_categoria_arbitro_check CHECK (((categoria_arbitro)::text = ANY ((ARRAY['AVANZADO'::character varying, 'INTERMEDIO'::character varying, 'PRINCIPAL_1'::character varying, 'PRINCIPAL_2'::character varying, 'PRINCIPAL_3'::character varying, 'PRINCIPAL_4'::character varying, 'ASISTENTE'::character varying, 'INICIAL'::character varying])::text[])))
);


ALTER TABLE public.designados OWNER TO develop;

--
-- Name: designados_id_designados_seq; Type: SEQUENCE; Schema: public; Owner: develop
--

ALTER TABLE public.designados ALTER COLUMN id_designados ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.designados_id_designados_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deudas_gasto; Type: TABLE; Schema: public; Owner: develop
--

CREATE TABLE public.deudas_gasto (
    id_deuda bigint NOT NULL,
    estado character varying(20),
    monto_asignado numeric(12,2),
    monto_pagado numeric(12,2),
    id_arbitro bigint,
    id_transaccion_gasto bigint
);


ALTER TABLE public.deudas_gasto OWNER TO develop;

--
-- Name: deudas_gasto_id_deuda_seq; Type: SEQUENCE; Schema: public; Owner: develop
--

ALTER TABLE public.deudas_gasto ALTER COLUMN id_deuda ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deudas_gasto_id_deuda_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pagos_prestamo; Type: TABLE; Schema: public; Owner: develop
--

CREATE TABLE public.pagos_prestamo (
    id_transaccion bigint NOT NULL,
    id_prestamoh bigint
);


ALTER TABLE public.pagos_prestamo OWNER TO develop;

--
-- Name: prestamo; Type: TABLE; Schema: public; Owner: develop
--

CREATE TABLE public.prestamo (
    id_prestamo bigint NOT NULL,
    estado character varying(20) NOT NULL,
    fecha_registro date NOT NULL,
    fecha_solicitud date,
    monto_devuelto numeric(12,2) NOT NULL,
    monto_solicitado numeric(12,2) NOT NULL,
    arbitro_id bigint NOT NULL
);


ALTER TABLE public.prestamo OWNER TO develop;

--
-- Name: prestamo_id_prestamo_seq; Type: SEQUENCE; Schema: public; Owner: develop
--

ALTER TABLE public.prestamo ALTER COLUMN id_prestamo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prestamo_id_prestamo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suspencion; Type: TABLE; Schema: public; Owner: develop
--

CREATE TABLE public.suspencion (
    id_suspencion bigint NOT NULL,
    cantidad_dias integer NOT NULL,
    fecha_fin timestamp(6) without time zone,
    fecha_incidente timestamp(6) without time zone,
    fecha_registro timestamp(6) without time zone,
    motivo character varying(255),
    tipo_suspencion integer NOT NULL,
    id_arbitroh bigint,
    id_canchah bigint
);


ALTER TABLE public.suspencion OWNER TO develop;

--
-- Name: suspencion_id_suspencion_seq; Type: SEQUENCE; Schema: public; Owner: develop
--

ALTER TABLE public.suspencion ALTER COLUMN id_suspencion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suspencion_id_suspencion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tbl_aranceles; Type: TABLE; Schema: public; Owner: develop
--

CREATE TABLE public.tbl_aranceles (
    id_arancel bigint NOT NULL,
    activo boolean NOT NULL,
    cantidad_partidos integer NOT NULL,
    descripcion character varying(255),
    fecha_vigencia date,
    monto_total numeric(38,2),
    id_canchah bigint
);


ALTER TABLE public.tbl_aranceles OWNER TO develop;

--
-- Name: tbl_aranceles_id_arancel_seq; Type: SEQUENCE; Schema: public; Owner: develop
--

ALTER TABLE public.tbl_aranceles ALTER COLUMN id_arancel ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tbl_aranceles_id_arancel_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transacciones; Type: TABLE; Schema: public; Owner: develop
--

CREATE TABLE public.transacciones (
    id_transaccion bigint NOT NULL,
    descripcion text NOT NULL,
    fecha_registro timestamp(6) without time zone NOT NULL,
    fecha_transaccion date,
    monto numeric(12,2) NOT NULL,
    tipo character varying(10) NOT NULL,
    id_cajah bigint
);


ALTER TABLE public.transacciones OWNER TO develop;

--
-- Name: transacciones_gasto; Type: TABLE; Schema: public; Owner: develop
--

CREATE TABLE public.transacciones_gasto (
    requiere_recupero boolean,
    id_transaccion bigint NOT NULL,
    concepto_gasto_id_h integer NOT NULL
);


ALTER TABLE public.transacciones_gasto OWNER TO develop;

--
-- Name: transacciones_id_transaccion_seq; Type: SEQUENCE; Schema: public; Owner: develop
--

ALTER TABLE public.transacciones ALTER COLUMN id_transaccion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transacciones_id_transaccion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transacciones_recupero; Type: TABLE; Schema: public; Owner: develop
--

CREATE TABLE public.transacciones_recupero (
    id_transaccion bigint NOT NULL,
    id_deuda_gasto bigint NOT NULL
);


ALTER TABLE public.transacciones_recupero OWNER TO develop;

--
-- Data for Name: arbitro; Type: TABLE DATA; Schema: public; Owner: develop
--

COPY public.arbitro (id_arbitro, apellido, categoria, contrasenia, disponible_domingo, disponible_sabado, estado_sistema, nombre, talle_camiseta, talle_short, whatsapp, tiene_auto) FROM stdin;
25	Silvero	AVANZADO	$2a$10$wRl4KhVDpWBvgr.TKgdRR.MpmqUdVwRz4EO.kPjmlXy7H/wYs1HKC	f	f	f	Oscar	XL	L	+5493743162738	t
16	Ferreyra	ASISTENTE	$2a$10$MBJ42xfnZFfi3kd5EzzZJeddGgRJ/MSFKlpe5fQUnJCH1Jl0b/S06	t	f	t	German	XL	XL	+54 9 3743 56-3874	t
26	Silvero	AVANZADO	$2a$10$r1HhsWXKbvLkb6J8bQIdbu.NqJRpbSwERVh9EYMTAx63xC696Zxn2	f	f	f	Yoselin	L	M	+5493743495867	t
27	Sosa	ASISTENTE	$2a$10$WZONShljHaqJ2FQ5H7a9Telm7g0j4KGOiOwLJmiARBbDSx0aevrES	f	t	t	Valeria	S	S	+54 9 3743 44-8311	t
32	Ortiz	ASISTENTE	$2a$10$o4RCMq7/IpDJbuJMLjWiBOETryZXPIRywfcwWAcpHmh60zgh.fZO.	t	t	t	Lourdes	M	M	+54 9 3743 60-3966	t
17	Gauto	AVANZADO	$2a$10$CzOr5nydYEw1k9rFEDaSGegZahDZVxbwh5ulId2FNHuX6Hsai6JMi	f	f	f	Ramón	M	M	+5493743738291	t
19	Marocheski	ASISTENTE	$2a$10$C2zF84AmQMInJaYb0onOR.ST.UcUjIO0PBdmbPOjKYY7ya/g4D9M.	f	t	t	Griselda	M	M	+54 9 3743 56-8868	t
15	Ferreira	AVANZADO	$2a$10$LZLTxgM1evBZlwmuyUAEeOynxkGtiuzvkx.35ghpky8X09O3WlngS	t	t	t	Ramón	XL	XL	+54 9 3743 63-1845	t
30	Diaz	AVANZADO	$2a$10$M0v6jlKIAZ/QNT8qhElc0.XW4C9QFbQ5JOkXh0iqK35nZRjuL2P/C	t	f	t	Raul	XL	L	+54 9 3764 76-0025	t
20	Mora	AVANZADO	$2a$10$Xol99XjR74syjRxD0.9KzOXaRf8XddOajnZcHgT5sA6PuKFujEWsi	f	f	f	Luciana	L	L	+5493743918273	t
18	Lovera	AVANZADO	$2a$10$R46SWR9CdvdWIOKKk5RnNubqbqjQK6BMFmu6tcrDaK337ToJptqsi	f	t	t	Andrés	XL	L	+54 9 3743 48-7344	t
5	Barboza	AVANZADO	$2a$10$pGfxn0XWU/SHikRbDea8HuaWnwoorONOk3ymWNkryJ2vnmsX99uCi	f	t	t	Diego	L	L	+54 9 3743 56-2056	t
29	Villalba	AVANZADO	$2a$10$ufRm2xmow/CXXFFbojJ4hOwyADBf6FFvtAT0CJ0caAuqAyyBHrily	t	t	t	Diego	XXL	XXL	+5493743293847	t
14	Ferreira	INTERMEDIO	$2a$10$UoZRMLuxzRH4GG0xTYpna.B3q5Vi3R1I3SQPT1MznuRN5Vl1oKYZm	f	t	t	Bruno	XL	L	+5493743614796	t
1	Alberto	AVANZADO	$2a$10$J56vYZp1UZCuBeUXTImRfeP6TyFwNXbzLQfIiauvGb54PQQ0d0SYq	f	f	f	Gauto	X	X	+5493743451023	t
31	Cubillas	AVANZADO	$2a$10$utllz.pbZ0B6luHyLGOFmel2DWobJjmHCkDrQzDMZYDoT3yyoEh/i	f	t	t	Claudio	XL	L	+5493743602289	t
3	Arias	AVANZADO	$2a$10$oR8HApgIJGQ.uSLpU/RuzeK4sR7tNFc1KU/fzmM3qpzjEwr82Q9n2	f	f	f	Silvestre	L	L	+5493743764589	t
10	Britos	AVANZADO	$2a$10$4L0jUxWYKTi19JjVKUHSduU.L4KZnZENNsE5L4pi/AJh.vzAduYC6	f	f	f	Javier	M	M	+5493743675421	t
4	Argüello	AVANZADO	$2a$10$zllHIv/jpEj/qW2ID6KmJ.251PWMEZD9g45RBwB2juwhRp25Ue1.m	f	f	f	Andrea	M	M	+5493743238945	t
21	Morel	AVANZADO	$2a$10$v1g3onugHAYSDbu8E2/J..7hM7Sn8sxoQPkwW4If5Yn6UmAcyZKzO	t	t	t	Ramón	XL	XL	+54 9 3743 41-1034	t
11	Días	AVANZADO	$2a$10$oZDe6Z2LRyoB8L6WrQ8IWuairPnDrB082ccVvokgqvdeHuk7FyyIK	t	t	t	Juan Carlos	X	X	+54 9 3743 51-6853	t
23	Palacios	AVANZADO	$2a$10$CHyPrBrZ44Bgg0J5/zYvdeV2qrnPcuTLDxctefE9XWwxCNxIwW68S	t	t	t	Sérgio	L	L	+54 9 3743 55-3550	t
2	Almirón	AVANZADO	$2a$10$nYR.UD2R3v5nrCp6WzNKJ.i.YXpjUirq5d2QnZ9i7GGpbnc3ZS3yG	t	f	t	Oscar	XL	XL	+54 9 3743 51-9317	t
13	Espinola	AVANZADO	$2a$10$v6ZWoZIq0TISUV/ogF4lDOQk/VEC11rrNzKBtRKXsm4rKURegQP9e	t	f	t	Pablo	L	L	+5493743456789	t
7	Bogado	AVANZADO	$2a$10$V6bnxixEWHr2n8aaWF2o5OVvEruudttjeFhuB6mpdrBGneEbp3FGa	f	f	t	Hugo	L	L	+5493743349012	t
33	Gonzales	ASISTENTE	$2a$10$CnRKzUpDAGu/m.cx1zIxcOjTH53iC6Y4s.BS7ZdLb1hmMvU2yBuyy	f	t	t	Alejandro	M	M	+54 9 3765 52-7928	t
22	Nimeth	ASISTENTE	$2a$10$StNfE.a2v/oOZk7M85Lw9OH8cIl5YPIODMrIAGe3p0yBwYmsk4XrC	t	t	t	Pablo	XXL	XXL	+54 9 3743 53-8078	t
12	Espínola	ASISTENTE	$2a$10$ffM3mhuZPCMDoMgOg5Bi/O35ZDEum3dkositTOOc3q1NBjLhaEVnG	f	f	t	Belen	M	M	+5493743210984	t
24	Rivas	AVANZADO	$2a$10$jye5vRW5Zpg5qXjZPtVaN.XUkheNZ4XBPJaU/jrsWwDHHASwaKjei	t	f	t	Jorge	XL	XL	+54 9 3743 56-5514	t
8	Brítez	AVANZADO	$2a$10$qXQzOlACXn8ffToWps9n9O9Uk0xC94x2oZGqPvi8gpoP9pfGnbX5q	t	t	t	Alberto	XL	XL	+54 9 11 5342-8466	t
9	Brítez	AVANZADO	$2a$10$.EaPug0H9I3ylKS6RSUF6ulpshYlE97UCnwZZ.PTbCAdEjxsQvIES	f	t	t	Dario	XXXL	XXL	+54 9 3743 55-8331	t
34	Mendoza	AVANZADO	$2a$10$ByU9QzE7LoPSmBkBjps2bel7MOux.VDhIKhuuhzOnvC1Ge15aHzIe	f	t	t	Hector	M	M	+5493743452732	t
6	Benítez	AVANZADO	$2a$10$gqcKZzvijzchmXjSuoyI8uOJrbqzPB.Gj56B.iLH3CZf/tLvUpPJ.	t	t	t	Juan	XL	XL	+54 9 3743 61-7001	t
28	Vázquez	AVANZADO	$2a$10$ytF201HGLQ/uXyZkFlUrIek45uNqb36Xm0kmOiUqSxigVxSWc.bNi	f	t	t	Roberto	L	L	+54 9 3743 61-2712	t
\.


--
-- Data for Name: caja; Type: TABLE DATA; Schema: public; Owner: develop
--

COPY public.caja (id_caja, activo, anio, nombre, saldo_actual) FROM stdin;
2	t	2026	Caja inicio de año	114567.00
\.


--
-- Data for Name: cancha; Type: TABLE DATA; Schema: public; Owner: develop
--

COPY public.cancha (id_cancha, categoria, estado, fuera_de_juego, nombre_cancha, necesita_viaje) FROM stdin;
1	FUTBOL_11	t	f	Master de Jardín	t
2	FUTBOL_10	t	f	Master de Santo Pipó	t
3	FUTBOL_9	t	f	PapiFutbol Santo Pipó	t
4	FUTBOL_10	t	f	Veteranos Corpus	t
5	FUTBOL_9	t	f	Capilla	t
6	FUTBOL_9	t	f	Independiente	t
7	FUTBOL_9	t	f	Predio Nuevo	t
8	FUTBOL_11	t	t	Oasis	t
\.


--
-- Data for Name: concepto_gasto; Type: TABLE DATA; Schema: public; Owner: develop
--

COPY public.concepto_gasto (id_concepto_gasto, descripcion, nombre) FROM stdin;
1	Gastos de traslado .	Combustible / Viáticos
2	Gastos destinados a celebraciones, reuniones sociales o la cena anual del grupo.	Cena / Agasajo 
3	Compra de tarjetas, silbatos, planillas, indumentaria oficial, banderines o intercomunicadores.	Indumentaria y Equipamiento
4	Pago a instructores, material didáctico, alquiler de salones o cursos de actualización de reglas de juego.	Capacitación y Cursos
5	Gastos en papelería, impresiones, fotocopias de planillas de votación o mantenimiento del espacio del grupo.	Insumos de Oficina y Administración
6	Dinero destinado a colaborar con algún miembro del grupo por cuestiones de salud, lesiones o fuerza mayor.	Ayuda Social / Fondo de Emergencia
7	Ingreso por la devolución o reintegro del dinero adelantado para combustible o pasajes de viajes.	Recuperación de Viáticos
8	Ingresos externos provenientes de marcas, publicidad en las camisetas o aportes extraordinarios de terceros.	Donaciones / Patrocinios
\.


--
-- Data for Name: designacion; Type: TABLE DATA; Schema: public; Owner: develop
--

COPY public.designacion (id_designacion, cantidad_partidos, estado_designacion, etapa_campeonato, fecha, id_canchah, detalle_extra, editable) FROM stdin;
84	6	2	FECHA_NORMAL	2026-03-22 07:30:00	5	Designación finalizada y sin detalle adicional	f
67	9	2	FECHA_NORMAL	2026-02-08 07:00:00	5	Designación finalizada y sin detalle adicional	f
27	4	3	FECHA_NORMAL	2026-07-11 12:30:00	2	Jornada suspendida y reprogramada	f
87	5	0	FECHA_NORMAL	2026-03-28 13:00:00	1	Designación creada correctamente y sin detalles	t
68	9	2	FECHA_NORMAL	2026-02-15 07:00:00	5	Designación finalizada y sin detalle adicional	f
70	9	2	FECHA_NORMAL	2026-03-01 07:45:00	5	Designación finalizada y sin detalle adicional	f
107	4	2	FECHA_NORMAL	2026-04-26 08:15:00	7	Designación finalizada y sin detalle adicional	f
89	5	2	FECHA_NORMAL	2026-04-04 12:00:00	3	Designación finalizada y sin detalle adicional	f
72	5	2	FECHA_NORMAL	2026-03-07 12:15:00	3	Designación finalizada y sin detalle adicional	f
73	4	2	FECHA_NORMAL	2026-03-07 14:00:00	2	Designación finalizada y sin detalle adicional	f
2	4	2	FECHA_NORMAL	2026-05-23 12:30:00	2	Detalle automatico	t
5	4	2	FECHA_NORMAL	2026-05-24 09:30:00	5	Detalle automatico	t
15	5	0	FECHA_NORMAL	2026-06-05 09:45:00	5	Detalle automatico	t
8	5	2	FECHA_NORMAL	2026-07-04 12:00:00	1	Detalle automatico	t
32	5	2	FECHA_NORMAL	2026-07-12 09:45:00	5	Detalle automatico	t
30	4	2	FECHA_NORMAL	2026-07-12 09:45:00	6	Detalle automatico	t
93	5	0	FECHA_NORMAL	2026-04-11 12:00:00	3	Designación creada correctamente y sin detalles	t
75	4	2	FECHA_NORMAL	2026-03-08 00:00:00	8	Designación finalizada y sin detalle adicional	f
76	5	0	FECHA_NORMAL	2026-03-14 13:00:00	1	Designación creada correctamente y sin detalles	t
78	4	1	FECHA_NORMAL	2026-03-14 14:00:00	2	Designación creada correctamente y sin detalles	t
39	4	3	FECHA_NORMAL	2026-05-30 11:30:00	2	Mal estado del campo de juego ( lluvia)	f
40	6	2	FECHA_NORMAL	2026-05-30 12:00:00	1	Designación finalizada y sin detalle adicional	f
43	5	3	FECHA_NORMAL	2026-05-31 09:45:00	6	Suspendido por lluvia	f
45	4	2	FECHA_NORMAL	2026-05-31 12:39:00	8	Designación finalizada y sin detalle adicional	f
47	5	2	FECHA_NORMAL	2026-06-06 11:39:00	3	Designación finalizada y sin detalle adicional	f
49	4	2	FECHA_NORMAL	2026-06-07 09:45:00	5	Designación finalizada y sin detalle adicional	f
51	4	2	FECHA_NORMAL	2026-06-07 12:30:00	8	Designación finalizada y sin detalle adicional	f
53	5	2	FECHA_NORMAL	2026-06-13 12:00:00	1	Designación finalizada y sin detalle adicional	f
56	5	2	FECHA_NORMAL	2026-06-14 09:45:00	5	Designación finalizada y sin detalle adicional	f
61	1	3	FECHA_NORMAL	2026-06-27 08:00:00	3	Suspendida por lluvia	f
80	4	2	FECHA_NORMAL	2026-03-15 12:00:00	8	Designación finalizada y sin detalle adicional	f
64	4	3	FECHA_NORMAL	2026-06-28 12:30:00	8	Suspendido por lluvia	f
65	4	3	FECHA_NORMAL	2026-06-28 09:45:00	6	Suspendido por lluvia	f
35	5	2	SEMIFINAL	2026-07-18 11:15:00	3	Designación finalizada y sin detalle adicional	f
37	4	2	FECHA_NORMAL	2026-07-18 12:45:00	4	Designación finalizada y sin detalle adicional	f
81	5	0	FECHA_NORMAL	2026-03-21 13:00:00	1	Designación creada correctamente y sin detalles	t
95	5	2	FECHA_NORMAL	2026-04-12 08:30:00	5	Designación finalizada y sin detalle adicional	f
83	5	2	FECHA_NORMAL	2026-03-21 12:00:00	3	Designación finalizada y sin detalle adicional	f
82	4	1	FECHA_NORMAL	2026-03-21 13:30:00	2	Designación creada correctamente y sin detalles	t
108	4	1	FECHA_NORMAL	2026-05-02 13:30:00	2	Designación creada correctamente y sin detalles	t
97	4	2	FECHA_NORMAL	2026-04-18 13:00:00	2	Designación finalizada y sin detalle adicional	f
124	4	3	FECHA_NORMAL	2026-07-25 12:30:00	2	\N	t
99	4	2	FECHA_NORMAL	2026-04-19 08:15:00	5	Designación finalizada y sin detalle adicional	f
111	5	2	FECHA_NORMAL	2026-05-10 08:15:00	7	Designación finalizada y sin detalle adicional	f
101	4	2	FECHA_NORMAL	2026-04-19 08:15:00	7	Designación finalizada y sin detalle adicional	f
104	5	0	FECHA_NORMAL	2026-04-25 11:45:00	3	Designación creada correctamente y sin detalles	t
102	4	1	FECHA_NORMAL	2026-04-25 13:00:00	2	Designación creada correctamente y sin detalles	t
114	5	0	FECHA_NORMAL	2026-05-16 11:45:00	3	Designación creada correctamente y sin detalles	t
115	4	1	FECHA_NORMAL	2026-05-17 08:15:00	5	Designación creada correctamente y sin detalles	t
36	3	2	FECHA_NORMAL	2026-07-19 10:45:00	5	Designación finalizada y sin detalle adicional	f
121	4	2	FECHA_NORMAL	2026-07-25 12:45:00	4	Designación finalizada y sin detalle adicional	f
127	4	1	FECHA_NORMAL	2026-07-26 12:45:00	8	Designación aceptada	t
86	5	0	FECHA_NORMAL	2026-03-28 12:00:00	3	Designación creada correctamente y sin detalles	t
66	4	3	FECHA_NORMAL	2026-06-20 00:00:00	2	Suspendido por lluvia	f
62	4	3	FECHA_NORMAL	2026-06-27 00:00:00	2	Suspendido por lluvia	f
60	5	3	FECHA_NORMAL	2026-06-27 12:00:00	1	Suspendida por lluvia	f
100	4	2	FECHA_NORMAL	2026-04-19 11:00:00	8	Designación finalizada y sin detalle adicional	f
63	5	3	FECHA_NORMAL	2026-06-28 09:45:00	5	Suspendido por lluvia	f
88	5	2	FECHA_NORMAL	2026-03-29 08:30:00	5	Designación finalizada y sin detalle adicional	f
90	5	0	FECHA_NORMAL	2026-04-04 13:00:00	1	Designación creada correctamente y sin detalles	t
29	5	3	SEMIFINAL	2026-07-11 11:30:00	3	Jornada suspendida y reprogramada	f
92	5	0	FECHA_NORMAL	2026-04-11 13:00:00	1	Designación creada correctamente y sin detalles	t
103	5	0	FECHA_NORMAL	2026-04-25 12:00:00	1	Designación creada correctamente y sin detalles	t
91	4	2	FECHA_NORMAL	2026-04-11 13:30:00	2	Designación finalizada y sin detalle adicional	f
4	5	2	FECHA_NORMAL	2026-05-23 11:30:00	3	Detalle automatico	t
1	4	2	FECHA_NORMAL	2026-05-23 12:30:00	4	Detalle automatico	t
3	5	2	FECHA_NORMAL	2026-05-23 12:00:00	1	Detalle automatico	t
38	5	2	FECHA_NORMAL	2026-07-18 12:00:00	1	Designación finalizada y sin detalle adicional	f
28	4	2	FECHA_NORMAL	2026-07-11 12:30:00	4	Detalle automatico	t
6	5	2	FECHA_NORMAL	2026-05-24 09:30:00	6	Detalle automatico	t
94	4	2	FECHA_NORMAL	2026-04-12 08:00:00	7	Designación finalizada y sin detalle adicional	f
26	5	2	FECHA_NORMAL	2026-07-11 12:00:00	1	Detalle automatico	t
41	5	3	FECHA_NORMAL	2026-05-30 11:30:00	3	Mal estado del campo de juego (lluvia)	f
42	4	2	FECHA_NORMAL	2026-05-30 12:30:00	4	Designación finalizada y sin detalle adicional	f
44	4	3	FECHA_NORMAL	2026-05-31 09:45:00	5	Suspendido por lluvia	f
48	4	2	FECHA_NORMAL	2026-06-06 12:30:00	4	Designación finalizada y sin detalle adicional	f
46	5	2	FECHA_NORMAL	2026-06-06 12:00:00	1	Designación finalizada y sin detalle adicional	f
50	5	2	FECHA_NORMAL	2026-06-07 09:45:00	6	Designación finalizada y sin detalle adicional	f
7	4	2	FECHA_NORMAL	2026-05-24 00:30:00	8	Detalle automatico	t
69	5	2	FECHA_NORMAL	2026-02-28 12:15:00	3	Designación finalizada y sin detalle adicional	f
31	4	2	FINAL	2026-07-12 12:30:00	8	Detalle automatico	t
11	4	2	FECHA_NORMAL	2026-06-27 12:30:00	4	Detalle automatico	t
9	4	2	FECHA_NORMAL	2026-07-04 12:30:00	2	Detalle automatico	t
14	4	2	FECHA_NORMAL	2026-07-04 12:30:00	4	Detalle automatico	t
10	5	2	CRUCES	2026-07-04 12:00:00	3	Detalle automatico	t
18	4	2	SEMIFINAL	2026-07-05 12:30:00	8	Detalle automatico	t
16	5	2	FECHA_NORMAL	2026-07-05 09:45:00	5	Detalle automatico	t
17	4	2	FECHA_NORMAL	2026-07-05 09:45:00	6	Detalle automatico	t
54	4	3	FECHA_NORMAL	2026-06-13 00:00:00	2	Suspendido por lluvia	f
52	4	2	FECHA_NORMAL	2026-06-13 12:30:00	4	Designación finalizada y sin detalle adicional	f
55	4	2	FECHA_NORMAL	2026-06-14 09:45:00	6	Designación finalizada y sin detalle adicional	f
57	4	2	FECHA_NORMAL	2026-06-14 12:30:00	8	Designación finalizada y sin detalle adicional	f
12	5	3	FECHA_NORMAL	2026-06-20 12:00:00	1	Suspendido por lluvia	f
13	4	2	FECHA_NORMAL	2026-06-20 12:30:00	4	Designación finalizada y sin detalle adicional	f
71	5	2	FECHA_NORMAL	2026-03-07 14:00:00	1	Designación finalizada y sin detalle adicional	f
74	9	2	FECHA_NORMAL	2026-03-08 07:30:00	5	Designación finalizada y sin detalle adicional	f
77	5	0	FECHA_NORMAL	2026-03-14 12:00:00	3	Designación creada correctamente y sin detalles	t
79	9	2	FECHA_NORMAL	2026-03-15 07:30:00	5	Designación finalizada y sin detalle adicional	f
116	1	1	FECHA_NORMAL	2026-05-17 08:15:00	6	Designación creada correctamente y sin detalles	t
85	4	2	FECHA_NORMAL	2026-03-22 12:00:00	8	Designación finalizada y sin detalle adicional	f
96	5	0	FECHA_NORMAL	2026-04-18 12:00:00	1	Designación finalizada y sin detalle adicional	t
98	5	2	FECHA_NORMAL	2026-04-18 11:45:00	3	Designación finalizada y sin detalle adicional	f
110	4	2	FECHA_NORMAL	2026-05-10 08:15:00	5	Designación finalizada y sin detalle adicional	f
106	4	2	FECHA_NORMAL	2026-04-26 11:00:00	8	Designación finalizada y sin detalle adicional	f
105	4	2	FECHA_NORMAL	2026-04-26 08:15:00	5	Designación finalizada y sin detalle adicional	f
112	4	2	FECHA_NORMAL	2026-05-10 11:00:00	8	Designación finalizada y sin detalle adicional	f
109	4	2	FECHA_NORMAL	2026-05-03 11:00:00	8	Designación finalizada y sin detalle adicional	f
113	5	0	FECHA_NORMAL	2026-05-16 12:00:00	1	Designación creada correctamente y sin detalles	t
117	4	2	FECHA_NORMAL	2026-05-17 11:00:00	8	Designación finalizada y sin detalle adicional	f
34	4	3	FECHA_NORMAL	2026-07-18 12:30:00	2	Jornada suspendida y reprogramada	f
120	8	1	FECHA_NORMAL	2026-07-26 08:00:00	5	Designación aceptada	t
122	5	3	FECHA_NORMAL	2026-07-25 12:00:00	1	\N	t
\.


--
-- Data for Name: designados; Type: TABLE DATA; Schema: public; Owner: develop
--

COPY public.designados (id_designados, categoria_arbitro, monto_percibido, partidos_dirigidos, id_arbitroh, id_designacionh) FROM stdin;
565	AVANZADO	0.00	0	23	127
122	AVANZADO	50000.00	4	28	28
144	AVANZADO	50000.00	4	29	28
125	AVANZADO	44000.00	5	11	26
127	AVANZADO	44000.00	5	5	26
133	AVANZADO	44000.00	5	31	26
140	AVANZADO	44000.00	5	23	26
51	INTERMEDIO	44000.00	4	21	18
52	PRINCIPAL_1	44000.00	4	11	18
53	PRINCIPAL_1	44000.00	4	23	18
54	PRINCIPAL_1	44000.00	5	24	16
55	PRINCIPAL_3	44000.00	5	30	16
56	PRINCIPAL_3	44000.00	5	7	16
57	PRINCIPAL_2	44000.00	5	5	16
58	PRINCIPAL_3	44000.00	4	29	17
59	PRINCIPAL_2	44000.00	4	6	17
60	ASISTENTE	44000.00	4	22	17
40	PRINCIPAL_3	44000.00	4	29	9
62	ASISTENTE	44000.00	4	19	9
73	PRINCIPAL_1	44000.00	4	23	9
48	INTERMEDIO	50000.00	4	8	14
67	PRINCIPAL_2	50000.00	4	5	14
70	PRINCIPAL_1	50000.00	4	11	14
71	AVANZADO	50000.00	4	34	14
33	INTERMEDIO	44000.00	5	21	8
34	PRINCIPAL_4	44000.00	5	2	8
35	PRINCIPAL_2	44000.00	5	6	8
36	ASISTENTE	44000.00	5	27	8
43	AVANZADO	37000.00	5	18	10
63	INTERMEDIO	37000.00	5	15	10
66	PRINCIPAL_3	37000.00	5	7	10
72	PRINCIPAL_2	37000.00	5	14	10
158	ASISTENTE	0.00	4	12	34
1	AVANZADO	0.00	4	9	2
2	PRINCIPAL_3	0.00	4	7	2
3	ASISTENTE	0.00	4	22	2
4	INTERMEDIO	0.00	5	21	3
5	PRINCIPAL_1	0.00	5	11	3
6	PRINCIPAL_3	0.00	5	29	3
7	INTERMEDIO	0.00	5	15	4
8	PRINCIPAL_1	0.00	5	23	4
9	PRINCIPAL_2	0.00	5	6	4
10	ASISTENTE	0.00	5	19	4
11	AVANZADO	0.00	4	31	1
12	PRINCIPAL_2	0.00	4	14	1
13	INTERMEDIO	0.00	4	8	1
14	ASISTENTE	0.00	5	33	3
15	PRINCIPAL_3	0.00	4	30	5
16	PRINCIPAL_1	0.00	4	24	5
18	PRINCIPAL_1	0.00	5	11	6
19	PRINCIPAL_1	0.00	5	23	6
20	PRINCIPAL_2	0.00	5	6	6
21	ASISTENTE	0.00	5	32	6
22	INTERMEDIO	0.00	4	21	7
23	AVANZADO	0.00	4	18	7
24	PRINCIPAL_4	0.00	4	2	7
25	AVANZADO	0.00	5	18	12
26	PRINCIPAL_1	0.00	5	11	12
27	PRINCIPAL_2	0.00	5	5	12
28	AVANZADO	0.00	5	9	12
29	INTERMEDIO	0.00	4	8	13
30	INTERMEDIO	0.00	4	21	13
31	PRINCIPAL_4	0.00	4	2	13
32	AVANZADO	0.00	4	34	13
37	PRINCIPAL_3	0.00	4	7	11
38	PRINCIPAL_1	0.00	4	23	11
39	INTERMEDIO	0.00	4	15	11
159	AVANZADO	0.00	4	7	34
160	AVANZADO	0.00	5	21	35
177	AVANZADO	0.00	3	24	36
181	AVANZADO	0.00	4	14	34
183	AVANZADO	11250.00	5	5	35
185	AVANZADO	16666.67	4	23	37
186	AVANZADO	16666.67	4	11	37
187	AVANZADO	0.00	5	18	38
104	INTERMEDIO	0.00	5	15	32
188	AVANZADO	0.00	5	29	38
190	AVANZADO	11250.00	5	15	35
109	PRINCIPAL_1	0.00	5	24	32
111	AVANZADO	0.00	4	18	31
193	AVANZADO	0.00	5	6	38
194	ASISTENTE	0.00	5	27	38
114	INTERMEDIO	0.00	4	8	31
115	PRINCIPAL_1	0.00	4	5	31
116	PRINCIPAL_1	0.00	4	11	30
118	INTERMEDIO	0.00	5	8	29
119	AVANZADO	0.00	5	7	32
198	AVANZADO	16666.67	4	8	37
128	AVANZADO	0.00	5	6	29
199	AVANZADO	11250.00	5	31	35
130	AVANZADO	0.00	4	14	27
131	AVANZADO	0.00	4	12	27
200	AVANZADO	16666.67	4	34	37
201	AVANZADO	0.00	6	14	40
202	AVANZADO	0.00	6	8	40
203	ASISTENTE	0.00	6	27	40
204	AVANZADO	0.00	4	29	39
205	AVANZADO	0.00	4	6	39
139	AVANZADO	0.00	5	34	29
143	AVANZADO	0.00	4	7	27
148	AVANZADO	0.00	4	6	30
150	AVANZADO	0.00	5	21	32
151	ASISTENTE	0.00	4	32	30
206	AVANZADO	0.00	4	5	39
207	AVANZADO	16666.67	4	15	42
208	AVANZADO	16666.67	4	7	42
209	AVANZADO	11250.00	5	9	41
210	AVANZADO	11250.00	5	11	41
213	AVANZADO	0.00	4	23	45
215	AVANZADO	0.00	4	7	45
216	AVANZADO	0.00	5	6	43
221	AVANZADO	0.00	4	24	44
566	AVANZADO	0.00	0	8	127
211	AVANZADO	11250.00	5	2	41
218	AVANZADO	0.00	5	29	43
567	AVANZADO	0.00	0	13	127
17	INTERMEDIO	0.00	4	15	5
121	AVANZADO	50000.00	4	18	28
117	INTERMEDIO	0.00	5	21	29
212	AVANZADO	11250.00	5	21	41
214	AVANZADO	0.00	4	5	45
217	AVANZADO	0.00	5	2	43
219	ASISTENTE	0.00	5	32	43
220	AVANZADO	0.00	4	15	44
222	AVANZADO	0.00	4	13	44
223	AVANZADO	0.00	6	23	40
224	AVANZADO	16666.67	4	18	42
225	AVANZADO	11250.00	5	21	47
226	AVANZADO	11250.00	5	8	47
227	AVANZADO	11250.00	5	7	47
228	AVANZADO	11250.00	5	2	47
229	AVANZADO	0.00	5	18	46
230	AVANZADO	0.00	5	14	46
231	AVANZADO	0.00	5	6	46
232	ASISTENTE	0.00	5	22	46
233	AVANZADO	16666.67	4	23	48
234	AVANZADO	16666.67	4	11	48
235	ASISTENTE	16666.67	4	12	48
236	AVANZADO	0.00	4	15	49
237	AVANZADO	0.00	4	24	49
238	AVANZADO	0.00	4	13	49
239	AVANZADO	0.00	4	18	51
240	AVANZADO	0.00	4	21	51
241	AVANZADO	0.00	4	8	51
242	AVANZADO	0.00	5	29	50
243	AVANZADO	0.00	5	6	50
244	AVANZADO	0.00	5	2	50
245	ASISTENTE	0.00	5	32	50
246	AVANZADO	0.00	5	28	53
247	AVANZADO	0.00	5	23	53
248	AVANZADO	0.00	5	31	53
249	AVANZADO	0.00	5	21	53
250	AVANZADO	16666.67	4	18	52
251	AVANZADO	16666.67	4	9	52
252	AVANZADO	16666.67	4	5	52
253	AVANZADO	16666.67	4	34	52
254	AVANZADO	0.00	4	7	54
255	AVANZADO	0.00	4	6	54
256	ASISTENTE	0.00	4	19	54
257	AVANZADO	0.00	5	23	56
258	AVANZADO	0.00	5	30	56
259	AVANZADO	0.00	5	24	56
260	AVANZADO	0.00	5	15	56
261	AVANZADO	0.00	4	2	55
262	AVANZADO	0.00	4	7	55
263	AVANZADO	0.00	4	8	55
264	AVANZADO	0.00	4	18	57
265	AVANZADO	0.00	4	11	57
266	AVANZADO	0.00	4	13	57
271	AVANZADO	0.00	4	29	62
272	AVANZADO	0.00	4	14	62
273	ASISTENTE	0.00	4	19	62
274	AVANZADO	0.00	5	21	60
275	AVANZADO	0.00	5	2	60
276	AVANZADO	0.00	5	6	60
277	ASISTENTE	0.00	5	27	60
278	AVANZADO	0.00	1	18	61
279	AVANZADO	0.00	1	5	61
280	AVANZADO	0.00	1	9	61
281	AVANZADO	0.00	1	11	61
282	AVANZADO	0.00	1	34	61
283	AVANZADO	0.00	4	21	64
284	AVANZADO	0.00	4	11	64
285	AVANZADO	0.00	4	23	64
286	AVANZADO	0.00	3	7	36
287	AVANZADO	0.00	4	7	66
288	AVANZADO	0.00	4	6	66
289	ASISTENTE	0.00	4	19	66
294	AVANZADO	0.00	5	24	63
295	AVANZADO	0.00	5	30	63
296	AVANZADO	0.00	5	7	63
297	AVANZADO	0.00	5	5	63
298	AVANZADO	0.00	4	29	65
299	AVANZADO	0.00	4	6	65
300	ASISTENTE	0.00	4	22	65
301	AVANZADO	0.00	3	21	36
302	AVANZADO	0.00	0	29	67
303	AVANZADO	0.00	0	24	67
304	AVANZADO	0.00	0	7	67
305	AVANZADO	0.00	0	18	67
306	ASISTENTE	0.00	0	22	67
307	AVANZADO	0.00	0	11	67
308	AVANZADO	0.00	0	21	67
309	AVANZADO	0.00	0	28	68
310	AVANZADO	0.00	0	13	68
311	ASISTENTE	0.00	0	12	68
312	AVANZADO	0.00	0	23	68
313	ASISTENTE	0.00	0	32	68
314	AVANZADO	0.00	0	15	68
315	AVANZADO	0.00	0	8	68
316	AVANZADO	11250.00	0	6	69
317	ASISTENTE	11250.00	0	22	69
318	AVANZADO	11250.00	0	7	69
319	AVANZADO	11250.00	0	23	69
320	AVANZADO	0.00	0	30	70
321	AVANZADO	0.00	0	21	70
322	AVANZADO	0.00	0	24	70
323	AVANZADO	0.00	0	15	70
324	AVANZADO	0.00	0	13	70
325	ASISTENTE	0.00	0	12	70
326	ASISTENTE	11250.00	0	12	72
327	AVANZADO	11250.00	0	8	72
328	AVANZADO	11250.00	0	24	72
329	AVANZADO	11250.00	0	31	72
330	AVANZADO	0.00	0	5	71
331	AVANZADO	0.00	0	7	71
332	ASISTENTE	0.00	0	19	71
336	ASISTENTE	0.00	0	32	73
333	AVANZADO	0.00	0	11	71
334	AVANZADO	0.00	0	29	73
335	AVANZADO	0.00	0	21	73
339	AVANZADO	0.00	0	8	75
340	AVANZADO	0.00	0	15	74
341	ASISTENTE	0.00	0	22	74
342	ASISTENTE	0.00	0	16	74
343	AVANZADO	0.00	0	18	74
344	AVANZADO	0.00	0	11	74
345	AVANZADO	0.00	0	23	74
337	AVANZADO	0.00	0	13	75
338	AVANZADO	0.00	0	21	75
346	AVANZADO	0.00	0	11	78
347	AVANZADO	0.00	0	18	78
348	ASISTENTE	0.00	0	19	78
349	AVANZADO	11250.00	0	7	77
350	AVANZADO	11250.00	0	23	77
351	ASISTENTE	11250.00	0	22	77
352	AVANZADO	0.00	0	21	76
353	ASISTENTE	0.00	0	32	76
354	AVANZADO	0.00	0	24	79
355	AVANZADO	0.00	0	21	79
356	ASISTENTE	0.00	0	12	79
357	AVANZADO	0.00	0	7	79
358	AVANZADO	0.00	0	29	79
359	AVANZADO	0.00	0	23	79
360	AVANZADO	0.00	0	18	80
361	AVANZADO	0.00	0	8	80
362	AVANZADO	0.00	0	13	80
363	AVANZADO	11250.00	0	18	83
364	AVANZADO	11250.00	0	11	83
365	AVANZADO	11250.00	0	6	83
366	ASISTENTE	11250.00	0	32	83
367	AVANZADO	0.00	0	7	82
368	AVANZADO	0.00	0	21	82
369	ASISTENTE	0.00	0	22	82
370	AVANZADO	0.00	0	8	81
371	AVANZADO	0.00	0	28	81
372	ASISTENTE	0.00	0	19	81
373	AVANZADO	0.00	0	11	84
374	AVANZADO	0.00	0	24	84
376	AVANZADO	0.00	0	28	84
377	ASISTENTE	0.00	0	12	84
378	AVANZADO	0.00	0	21	85
379	AVANZADO	0.00	0	8	85
380	AVANZADO	0.00	0	23	85
381	AVANZADO	0.00	0	15	84
382	AVANZADO	0.00	0	7	87
383	AVANZADO	11250.00	0	8	86
384	ASISTENTE	11250.00	0	33	86
385	AVANZADO	11250.00	0	23	86
386	AVANZADO	0.00	0	21	88
387	AVANZADO	0.00	0	29	88
388	AVANZADO	0.00	0	24	88
389	AVANZADO	0.00	0	8	88
390	AVANZADO	0.00	0	21	90
391	ASISTENTE	0.00	0	12	90
392	AVANZADO	0.00	0	2	90
393	AVANZADO	11250.00	0	11	89
394	AVANZADO	11250.00	0	6	89
395	ASISTENTE	11250.00	0	32	89
396	AVANZADO	11250.00	0	23	89
397	AVANZADO	0.00	0	28	92
398	ASISTENTE	0.00	0	33	92
399	AVANZADO	0.00	0	8	92
400	ASISTENTE	0.00	0	12	91
401	AVANZADO	0.00	0	29	91
402	AVANZADO	0.00	0	18	91
403	ASISTENTE	11250.00	0	19	93
404	AVANZADO	11250.00	0	7	93
405	AVANZADO	0.00	0	23	95
406	AVANZADO	0.00	0	24	95
407	AVANZADO	0.00	0	29	95
408	AVANZADO	0.00	0	21	95
409	AVANZADO	0.00	0	15	94
410	AVANZADO	0.00	0	8	94
411	ASISTENTE	0.00	0	32	94
412	AVANZADO	0.00	0	23	96
416	AVANZADO	0.00	0	8	97
417	ASISTENTE	0.00	0	32	97
418	AVANZADO	0.00	0	15	97
419	AVANZADO	0.00	0	9	96
420	ASISTENTE	0.00	0	22	96
421	AVANZADO	11250.00	0	29	98
422	AVANZADO	11250.00	0	6	98
423	ASISTENTE	11250.00	0	12	98
424	AVANZADO	11250.00	0	2	98
425	AVANZADO	0.00	0	23	99
426	AVANZADO	0.00	0	24	99
427	AVANZADO	0.00	0	29	99
428	AVANZADO	0.00	0	2	99
429	AVANZADO	0.00	0	15	101
430	AVANZADO	0.00	0	8	101
431	ASISTENTE	0.00	0	32	101
432	AVANZADO	0.00	0	18	100
433	AVANZADO	0.00	0	28	100
434	AVANZADO	0.00	0	21	100
435	ASISTENTE	11250.00	0	19	104
436	AVANZADO	11250.00	0	8	104
437	AVANZADO	0.00	0	31	102
438	AVANZADO	0.00	0	23	102
439	AVANZADO	0.00	0	2	102
440	AVANZADO	0.00	0	7	103
441	ASISTENTE	0.00	0	12	103
442	AVANZADO	0.00	0	21	107
443	AVANZADO	0.00	0	29	107
444	ASISTENTE	0.00	0	22	107
445	AVANZADO	0.00	0	15	105
446	AVANZADO	0.00	0	24	105
447	AVANZADO	0.00	0	7	105
448	AVANZADO	0.00	0	11	105
449	AVANZADO	0.00	0	18	106
450	AVANZADO	0.00	0	8	106
451	AVANZADO	0.00	0	23	106
452	AVANZADO	0.00	0	29	108
453	AVANZADO	0.00	0	23	108
454	AVANZADO	0.00	0	2	108
455	AVANZADO	0.00	0	8	109
456	AVANZADO	0.00	0	23	109
457	ASISTENTE	0.00	0	12	109
458	ASISTENTE	0.00	0	22	111
459	AVANZADO	0.00	0	24	111
460	AVANZADO	0.00	0	23	111
461	AVANZADO	0.00	0	6	111
462	AVANZADO	0.00	0	15	110
463	ASISTENTE	0.00	0	32	110
464	AVANZADO	0.00	0	8	110
465	AVANZADO	0.00	0	13	112
466	AVANZADO	0.00	0	21	112
467	AVANZADO	0.00	0	2	112
468	AVANZADO	11250.00	0	18	114
472	AVANZADO	0.00	0	15	115
475	AVANZADO	0.00	0	7	116
476	AVANZADO	0.00	0	11	116
477	ASISTENTE	0.00	0	22	116
478	AVANZADO	0.00	0	8	117
479	AVANZADO	0.00	0	23	117
480	ASISTENTE	0.00	0	12	117
469	AVANZADO	11250.00	0	11	114
470	AVANZADO	0.00	0	8	113
471	AVANZADO	0.00	0	24	115
473	ASISTENTE	0.00	0	16	115
474	AVANZADO	0.00	0	2	115
489	AVANZADO	0.00	0	11	120
490	AVANZADO	0.00	0	15	120
491	AVANZADO	0.00	0	24	120
492	ASISTENTE	0.00	0	22	120
516	AVANZADO	16666.67	0	9	121
531	AVANZADO	0.00	0	21	122
541	AVANZADO	16666.67	0	18	121
546	AVANZADO	0.00	0	8	122
548	ASISTENTE	0.00	0	19	122
550	AVANZADO	16666.67	0	31	121
551	INTERMEDIO	0.00	0	14	122
557	AVANZADO	0.00	0	23	124
558	AVANZADO	0.00	0	29	124
562	ASISTENTE	0.00	0	32	124
563	AVANZADO	0.00	0	30	120
564	AVANZADO	0.00	0	21	120
\.


--
-- Data for Name: deudas_gasto; Type: TABLE DATA; Schema: public; Owner: develop
--

COPY public.deudas_gasto (id_deuda, estado, monto_asignado, monto_pagado, id_arbitro, id_transaccion_gasto) FROM stdin;
\.


--
-- Data for Name: pagos_prestamo; Type: TABLE DATA; Schema: public; Owner: develop
--

COPY public.pagos_prestamo (id_transaccion, id_prestamoh) FROM stdin;
11	9
12	3
\.


--
-- Data for Name: prestamo; Type: TABLE DATA; Schema: public; Owner: develop
--

COPY public.prestamo (id_prestamo, estado, fecha_registro, fecha_solicitud, monto_devuelto, monto_solicitado, arbitro_id) FROM stdin;
1	PENDIENTE	2026-07-11	2025-12-20	0.00	10000.00	20
2	PENDIENTE	2026-07-11	2025-02-02	0.00	65000.00	15
4	PENDIENTE	2026-07-11	2025-01-01	0.00	20000.00	11
5	PENDIENTE	2026-07-11	2025-05-05	0.00	60000.00	2
6	PENDIENTE	2026-07-11	2025-05-05	0.00	30000.00	8
7	PENDIENTE	2026-07-11	2025-05-05	0.00	8000.00	12
8	PENDIENTE	2026-07-11	2025-05-05	0.00	10000.00	18
10	PENDIENTE	2026-07-11	2025-06-06	0.00	90000.00	26
9	PAGADO	2026-07-11	2025-05-05	25000.00	25000.00	29
3	PENDIENTE	2026-07-11	2025-06-05	10000.00	74000.00	14
\.


--
-- Data for Name: suspencion; Type: TABLE DATA; Schema: public; Owner: develop
--

COPY public.suspencion (id_suspencion, cantidad_dias, fecha_fin, fecha_incidente, fecha_registro, motivo, tipo_suspencion, id_arbitroh, id_canchah) FROM stdin;
2	0	2026-07-17 00:00:00	2026-07-17 00:00:00	2026-07-24 19:41:35.306707	Mál desempeño, a la proxima se emitirá desde comision de master, una sancion correspondiente!	1	11	1
3	14	2026-07-31 00:00:00	2026-07-17 00:00:00	2026-07-24 23:40:33.639166	Suspencion de 14 días por mal desempeño arbitral!	2	5	1
\.


--
-- Data for Name: tbl_aranceles; Type: TABLE DATA; Schema: public; Owner: develop
--

COPY public.tbl_aranceles (id_arancel, activo, cantidad_partidos, descripcion, fecha_vigencia, monto_total, id_canchah) FROM stdin;
1	t	5	Primer Arancel del torneo	2026-07-13	45000.00	3
2	t	4	Primer Campeonato	2026-07-13	50000.00	4
\.


--
-- Data for Name: transacciones; Type: TABLE DATA; Schema: public; Owner: develop
--

COPY public.transacciones (id_transaccion, descripcion, fecha_registro, fecha_transaccion, monto, tipo, id_cajah) FROM stdin;
1	Préstamo otorgado al árbitro : Mora Luciana	2026-07-11 16:33:57.792969	2025-12-20	10000.00	EGRESO	2
2	Préstamo otorgado al árbitro : Ferreira Ramón	2026-07-11 16:34:12.419995	2025-02-02	65000.00	EGRESO	2
3	Préstamo otorgado al árbitro : Ferreira Bruno	2026-07-11 16:34:28.75218	2025-06-05	74000.00	EGRESO	2
4	Préstamo otorgado al árbitro : Días Juan Carlos	2026-07-11 16:34:52.625471	2025-01-01	20000.00	EGRESO	2
5	Préstamo otorgado al árbitro : Almirón Oscar	2026-07-11 16:35:11.244663	2025-05-05	60000.00	EGRESO	2
6	Préstamo otorgado al árbitro : Brítez Alberto	2026-07-11 16:35:26.445502	2025-05-05	30000.00	EGRESO	2
7	Préstamo otorgado al árbitro : Espínola Belen	2026-07-11 16:35:54.40976	2025-05-05	8000.00	EGRESO	2
8	Préstamo otorgado al árbitro : Lovera Andrés	2026-07-11 16:36:09.782697	2025-05-05	10000.00	EGRESO	2
9	Préstamo otorgado al árbitro : Villalba Diego	2026-07-11 16:36:25.161622	2025-05-05	25000.00	EGRESO	2
10	Préstamo otorgado al árbitro : Silvero Yoselin	2026-07-11 16:36:43.012276	2025-06-06	90000.00	EGRESO	2
11	Pago de préstamo Villalba Diego	2026-07-11 16:37:05.29456	2026-07-11	25000.00	INGRESO	2
12	Pago de préstamo Ferreira Bruno	2026-07-11 16:37:23.964396	2026-07-11	10000.00	INGRESO	2
13	JORANDA EN PIPO QUE NO SALIO	2026-07-11 16:43:20.744668	2026-01-11	20000.00	EGRESO	2
14	Gasto en materiales del quincho	2026-07-11 16:44:11.067939	2026-01-18	17200.00	EGRESO	2
15	Almuerzo dia de arreglo del quincho	2026-07-11 16:44:36.519448	2025-01-18	20000.00	EGRESO	2
16	Choripanes 	2026-07-11 16:45:24.268306	2026-01-23	23570.00	EGRESO	2
\.


--
-- Data for Name: transacciones_gasto; Type: TABLE DATA; Schema: public; Owner: develop
--

COPY public.transacciones_gasto (requiere_recupero, id_transaccion, concepto_gasto_id_h) FROM stdin;
f	13	7
f	14	6
f	15	2
f	16	2
\.


--
-- Data for Name: transacciones_recupero; Type: TABLE DATA; Schema: public; Owner: develop
--

COPY public.transacciones_recupero (id_transaccion, id_deuda_gasto) FROM stdin;
\.


--
-- Name: arbitro_id_arbitro_seq; Type: SEQUENCE SET; Schema: public; Owner: develop
--

SELECT pg_catalog.setval('public.arbitro_id_arbitro_seq', 34, true);


--
-- Name: caja_id_caja_seq; Type: SEQUENCE SET; Schema: public; Owner: develop
--

SELECT pg_catalog.setval('public.caja_id_caja_seq', 2, true);


--
-- Name: cancha_seq; Type: SEQUENCE SET; Schema: public; Owner: develop
--

SELECT pg_catalog.setval('public.cancha_seq', 51, true);


--
-- Name: concepto_gasto_id_concepto_gasto_seq; Type: SEQUENCE SET; Schema: public; Owner: develop
--

SELECT pg_catalog.setval('public.concepto_gasto_id_concepto_gasto_seq', 8, true);


--
-- Name: designacion_id_designacion_seq; Type: SEQUENCE SET; Schema: public; Owner: develop
--

SELECT pg_catalog.setval('public.designacion_id_designacion_seq', 127, true);


--
-- Name: designados_id_designados_seq; Type: SEQUENCE SET; Schema: public; Owner: develop
--

SELECT pg_catalog.setval('public.designados_id_designados_seq', 567, true);


--
-- Name: deudas_gasto_id_deuda_seq; Type: SEQUENCE SET; Schema: public; Owner: develop
--

SELECT pg_catalog.setval('public.deudas_gasto_id_deuda_seq', 1, false);


--
-- Name: prestamo_id_prestamo_seq; Type: SEQUENCE SET; Schema: public; Owner: develop
--

SELECT pg_catalog.setval('public.prestamo_id_prestamo_seq', 10, true);


--
-- Name: suspencion_id_suspencion_seq; Type: SEQUENCE SET; Schema: public; Owner: develop
--

SELECT pg_catalog.setval('public.suspencion_id_suspencion_seq', 3, true);


--
-- Name: tbl_aranceles_id_arancel_seq; Type: SEQUENCE SET; Schema: public; Owner: develop
--

SELECT pg_catalog.setval('public.tbl_aranceles_id_arancel_seq', 2, true);


--
-- Name: transacciones_id_transaccion_seq; Type: SEQUENCE SET; Schema: public; Owner: develop
--

SELECT pg_catalog.setval('public.transacciones_id_transaccion_seq', 16, true);


--
-- Name: arbitro arbitro_pkey; Type: CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.arbitro
    ADD CONSTRAINT arbitro_pkey PRIMARY KEY (id_arbitro);


--
-- Name: caja caja_pkey; Type: CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.caja
    ADD CONSTRAINT caja_pkey PRIMARY KEY (id_caja);


--
-- Name: cancha cancha_pkey; Type: CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.cancha
    ADD CONSTRAINT cancha_pkey PRIMARY KEY (id_cancha);


--
-- Name: concepto_gasto concepto_gasto_pkey; Type: CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.concepto_gasto
    ADD CONSTRAINT concepto_gasto_pkey PRIMARY KEY (id_concepto_gasto);


--
-- Name: designacion designacion_pkey; Type: CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.designacion
    ADD CONSTRAINT designacion_pkey PRIMARY KEY (id_designacion);


--
-- Name: designados designados_pkey; Type: CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.designados
    ADD CONSTRAINT designados_pkey PRIMARY KEY (id_designados);


--
-- Name: deudas_gasto deudas_gasto_pkey; Type: CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.deudas_gasto
    ADD CONSTRAINT deudas_gasto_pkey PRIMARY KEY (id_deuda);


--
-- Name: pagos_prestamo pagos_prestamo_pkey; Type: CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.pagos_prestamo
    ADD CONSTRAINT pagos_prestamo_pkey PRIMARY KEY (id_transaccion);


--
-- Name: prestamo prestamo_pkey; Type: CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.prestamo
    ADD CONSTRAINT prestamo_pkey PRIMARY KEY (id_prestamo);


--
-- Name: suspencion suspencion_pkey; Type: CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.suspencion
    ADD CONSTRAINT suspencion_pkey PRIMARY KEY (id_suspencion);


--
-- Name: tbl_aranceles tbl_aranceles_pkey; Type: CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.tbl_aranceles
    ADD CONSTRAINT tbl_aranceles_pkey PRIMARY KEY (id_arancel);


--
-- Name: transacciones_gasto transacciones_gasto_pkey; Type: CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.transacciones_gasto
    ADD CONSTRAINT transacciones_gasto_pkey PRIMARY KEY (id_transaccion);


--
-- Name: transacciones transacciones_pkey; Type: CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.transacciones
    ADD CONSTRAINT transacciones_pkey PRIMARY KEY (id_transaccion);


--
-- Name: transacciones_recupero transacciones_recupero_pkey; Type: CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.transacciones_recupero
    ADD CONSTRAINT transacciones_recupero_pkey PRIMARY KEY (id_transaccion);


--
-- Name: arbitro uk80x5s2o02o5nwgg3ro7br2ne8; Type: CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.arbitro
    ADD CONSTRAINT uk80x5s2o02o5nwgg3ro7br2ne8 UNIQUE (whatsapp);


--
-- Name: designados fk299mu507ego71yoy4qme7wiuq; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.designados
    ADD CONSTRAINT fk299mu507ego71yoy4qme7wiuq FOREIGN KEY (id_designacionh) REFERENCES public.designacion(id_designacion);


--
-- Name: pagos_prestamo fk5fpr6a8hpainfk1lyhu31wjd8; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.pagos_prestamo
    ADD CONSTRAINT fk5fpr6a8hpainfk1lyhu31wjd8 FOREIGN KEY (id_prestamoh) REFERENCES public.prestamo(id_prestamo);


--
-- Name: tbl_aranceles fk5nwbwkbsjl2vmklvaovppntm7; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.tbl_aranceles
    ADD CONSTRAINT fk5nwbwkbsjl2vmklvaovppntm7 FOREIGN KEY (id_canchah) REFERENCES public.cancha(id_cancha);


--
-- Name: suspencion fk60f9wwkb5dpws2de6lben5pw; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.suspencion
    ADD CONSTRAINT fk60f9wwkb5dpws2de6lben5pw FOREIGN KEY (id_canchah) REFERENCES public.cancha(id_cancha);


--
-- Name: suspencion fk9bb9p3y8hpcibk63canlb344t; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.suspencion
    ADD CONSTRAINT fk9bb9p3y8hpcibk63canlb344t FOREIGN KEY (id_arbitroh) REFERENCES public.arbitro(id_arbitro);


--
-- Name: transacciones_recupero fka00r35t26ne52uaohrsmb80ht; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.transacciones_recupero
    ADD CONSTRAINT fka00r35t26ne52uaohrsmb80ht FOREIGN KEY (id_transaccion) REFERENCES public.transacciones(id_transaccion);


--
-- Name: designacion fkd0la8lc9vdqbb3p86n7pw3jm9; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.designacion
    ADD CONSTRAINT fkd0la8lc9vdqbb3p86n7pw3jm9 FOREIGN KEY (id_canchah) REFERENCES public.cancha(id_cancha);


--
-- Name: deudas_gasto fkhlt4o0ydybaj3wdfkbpslqytn; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.deudas_gasto
    ADD CONSTRAINT fkhlt4o0ydybaj3wdfkbpslqytn FOREIGN KEY (id_transaccion_gasto) REFERENCES public.transacciones_gasto(id_transaccion);


--
-- Name: transacciones_recupero fkisbh4in4w55f3fqbg370467ih; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.transacciones_recupero
    ADD CONSTRAINT fkisbh4in4w55f3fqbg370467ih FOREIGN KEY (id_deuda_gasto) REFERENCES public.deudas_gasto(id_deuda);


--
-- Name: deudas_gasto fkjs32nexuir9ymofiufv9eaeus; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.deudas_gasto
    ADD CONSTRAINT fkjs32nexuir9ymofiufv9eaeus FOREIGN KEY (id_arbitro) REFERENCES public.arbitro(id_arbitro);


--
-- Name: transacciones fkkcsk08nx1h2wo9sbryyeu9c6; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.transacciones
    ADD CONSTRAINT fkkcsk08nx1h2wo9sbryyeu9c6 FOREIGN KEY (id_cajah) REFERENCES public.caja(id_caja);


--
-- Name: transacciones_gasto fkkd7g82s7eyte1dus0ykfs7oy5; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.transacciones_gasto
    ADD CONSTRAINT fkkd7g82s7eyte1dus0ykfs7oy5 FOREIGN KEY (concepto_gasto_id_h) REFERENCES public.concepto_gasto(id_concepto_gasto);


--
-- Name: pagos_prestamo fkkywbrlc76tu574sx9l0q4pl58; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.pagos_prestamo
    ADD CONSTRAINT fkkywbrlc76tu574sx9l0q4pl58 FOREIGN KEY (id_transaccion) REFERENCES public.transacciones(id_transaccion);


--
-- Name: prestamo fklichvnykcwphkoidn0tiic7wo; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.prestamo
    ADD CONSTRAINT fklichvnykcwphkoidn0tiic7wo FOREIGN KEY (arbitro_id) REFERENCES public.arbitro(id_arbitro);


--
-- Name: designados fkliqu3fjt0h29ish5ucydp8apc; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.designados
    ADD CONSTRAINT fkliqu3fjt0h29ish5ucydp8apc FOREIGN KEY (id_arbitroh) REFERENCES public.arbitro(id_arbitro);


--
-- Name: transacciones_gasto fkq7fa10741drv5ymlh3r88mrds; Type: FK CONSTRAINT; Schema: public; Owner: develop
--

ALTER TABLE ONLY public.transacciones_gasto
    ADD CONSTRAINT fkq7fa10741drv5ymlh3r88mrds FOREIGN KEY (id_transaccion) REFERENCES public.transacciones(id_transaccion);


--
-- PostgreSQL database dump complete
--

\unrestrict b9jSiXuuLPbTTalalLliZY65CE4iFfOflnQ65jZXEi9hJLY4oaxvzIWRnNTCSHA

