# ==========================================
# CONFIGURACIÓN DE BASE DE DATOS DE PRUEBAS (designaciones_test)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/designaciones_test
spring.datasource.username=develop
spring.datasource.password=develop123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# URL base de la DB principal/producción para la sincronización de snapshot
app.datasource.prod.url=jdbc:postgresql://localhost:5432/designaciones
app.datasource.prod.username=develop
app.datasource.prod.password=develop123

# Context / Config
server.port=8081
logging.level.com.designaciones.webdesignaciones=DEBUG
