spring.application.name=webdesignaciones
server.port=${PORT}
# ==========================================
# BASE DE DATOS (Supabase / Postgres)
# ==========================================
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}
spring.datasource.url=jdbc:postgresql://localhost:5432/designaciones
spring.datasource.username=develop
spring.datasource.password=develop123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# HikariCP Pool Config
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
# ==========================================
# ZONA HORARIA Y SERIALIZACIÓN
# ==========================================
app.timezone=America/Argentina/Buenos_Aires
spring.jackson.time-zone=America/Argentina/Buenos_Aires
spring.jpa.properties.hibernate.jdbc.time_zone=America/Argentina/Buenos_Aires
# ==========================================
# SEGURIDAD Y JWT
# ==========================================
JWT_SECRET=${JWT_SECRET}
JWT_PHONE=${JWT_PHONE}
JWT_GENERATOR=${JWT_GENERATOR}
# ==========================================
# SWAGGER & LOGGING
# ==========================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
logging.level.org.springdoc=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO