spring.application.name=webdesignaciones
# ==========================================
# CONFIGURACIÓN DEL DATASOURCE (SQLite)
# ==========================================
#spring.datasource.url=jdbc:sqlite:mibasededatos.sqlite
spring.datasource.url=jdbc:postgresql://localhost:5432/designaciones
spring.datasource.username=develop
spring.datasource.password=develop123
server.port=8081
# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
# Dialecto nativo de SQLite para Hibernate 6 (Spring Boot 3+)
#spring.jpa.database-platform=org.hibernate.community.dialect.PostgreSQLLegacyDialect
#spring.datasource.driver-class-name=org.postgresql.JDBC
spring.jpa.hibernate.ddl-auto=update
# Mostrar las consultas SQL en la consola (opcional, muy útil para debuggear)
spring.jpa.properties.hibernate.format_sql=true
# ==========================================
# CONFIGURACIÓN DE CORS
# ==========================================
cors.allowed-origins=http://localhost:5173
cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
cors.allowed-headers=*
cors.exposed-headers=Authorization,Content-Type
cors.allow-credentials=true
cors.max-age=3600
# Si tienes un context-path global:
#server.servlet.context-path=/api
security.jwt.private.user.phone=+543743614796
security.jwt.private.user.generator=bdevelop
security.jwt.private.key=61c3addc10f7461f4f37fca6bcfa1aef127b2440cedf86bd253155ceafec704f